#!/usr/bin/env python
# -*- coding: utf-8 -*-

from os import path
import sys

# Add the path of this executable to the system path
ROOT = path.join(path.abspath(path.dirname(__file__)), 'source')
sys.path.insert(0, ROOT)

from isping.main import Main

Main().run()

